spring.application.name=test-assignment

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/test_assignment_db}
spring.datasource.username=${DB_USER:henrik}
spring.datasource.password=${DB_PASS:henrik_password}
spring.sql.init.mode=always

# RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml

# Outbox Worker
outbox.poll.interval=5000